use online_learning_platform;


-- 1. total course purchase value for each student--
with value as(select s.student_id,s.full_name,sum(c.price) 
as course_purchase_value from students s join enrollments 
e on s.student_id=e.student_id join courses c on 
e.course_id=c.course_id group by s.student_id,s.full_name)
select student_id,full_name,course_purchase_value from value;

-- 2.find students whose total course value is higher than avg student value

with student_value as
(select s.student_id,s.full_name,sum(c.price) as total_course_value,count(e.enrollment_id) as enrolls
from  students s join enrollments e on s.student_id=e.student_id
join courses c on e.course_id=c.course_id
group by s.student_id,s.full_name)
select student_id,full_name,total_course_value from student_value
where total_course_value>(select avg(total_course_value) from student_value);




-- 3.rank students based on total course spending from high to low
select s.student_id,s.full_name ,sum(c.price) as course_spending,
rank() over(order by sum(c.price) desc) as ranking
from students s join enrollments e on s.student_id=e.student_id
join courses c on e.course_id=c.course_id group by s.student_id,
 s.full_name order by ranking asc;



-- 4.identify top10 high value students based on course spending
select s.student_id,s.full_name as high_value_students, 
sum(c.price) as course_spending from students s join 
enrollments e on s.student_id=e.student_id join courses c on
e.course_id=c.course_id group by s.student_id,s.full_name
order by course_spending desc limit 10;



-- 5.total revenue generated by each course

select c.course_id,c.course_name,count(e.enrollment_id)*c.price as revenue
from courses c join enrollments e on c.course_id=e.course_id
group by c.course_id,c.course_name;



-- 6.students who never progressed beyond 20% in any enrolled course--


select distinct s.student_id,s.full_name
from students s join enrollments e on s.student_id=e.student_id join course_progress cp
on e.enrollment_id=cp.enrollment_id group by s.student_id,s.full_name
having max(cp.completed_percent) <20;




-- 7.courses with highest avg completion %--

select course_id, course_name, avg_completion
from (select c.course_id, c.course_name, avg(cp.completed_percent) as avg_completion,
rank() over(order by avg(cp.completed_percent) desc) as rnk from courses c
join enrollments e on c.course_id = e.course_id
join course_progress cp on e.enrollment_id = cp.enrollment_id
group by c.course_id, c.course_name) t
where rnk = 1;


-- 8.categorize students into high,moderate,low engagement based on avg completion--

select s.student_id,s.full_name,avg(cp.completed_percent) as avg_completion,case 
when avg(cp.completed_percent) >55 then "High"
when avg(cp.completed_percent) >45 then "Moderate"
when avg(cp.completed_percent) <45 then "Low"
else "Poor"
end as Engagement_level
from  students s join enrollments e on s.student_id=e.student_id
join course_progress cp on e.enrollment_id=cp.enrollment_id
group by s.student_id,s.full_name;




-- 9.students who enrolled in courses but never started progress--

select s.student_id,s.full_name from students s join enrollments e
on s.student_id=e.student_id left join course_progress cp on e.enrollment_id=cp.enrollment_id
where cp.completed_percent =0;



-- 10.month wise enrollment count and complare it with previous month
select  distinct month(enroll_date) as month, count(*)  as course_enrolls
,lag(count(*)) over (order by month(enroll_date)) as Previous_month_enrolls
 from enrollments group by month(enroll_date) order by month;
 


 
 -- 11.month over month enrollment growth percentage--
 
SELECT month,enrollments,prev_enrollments,
ROUND((enrollments - prev_enrollments) * 100 / prev_enrollments, 2) AS growth_percent
FROM (SELECT monthname(enroll_date) AS month,COUNT(*) AS enrollments,
LAG(COUNT(*)) OVER (ORDER BY monthname(enroll_date)) AS prev_enrollments
FROM enrollments GROUP BY monthname(enroll_date)
order by month) t;

 
 -- 12.students whose course completion improved over time--
 
 SELECT DISTINCT student_id, full_name
FROM (SELECT s.student_id,s.full_name,cp.completed_percent,LAG(cp.completed_percent) OVER (
PARTITION BY s.student_id ORDER BY cp.last_accessed_date) AS prev_completion
FROM students s JOIN enrollments e ON s.student_id = e.student_id
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
) t
WHERE completed_percent > prev_completion;


 
 
 -- 13.courses with high enrollments but with lowest completion rates
 
 with low as
 (select distinct c.course_id,c.course_name,count(e.enrollment_id) as enrolls,
 avg(cp.completed_percent) as avg_completion from courses c join enrollments e
 on c.course_id=e.course_id join course_progress cp on e.enrollment_id=cp.enrollment_id
 group by c.course_id,c.course_name
 having count(e.enrollment_id)>60 and avg(cp.completed_percent)<45)
 select course_id,course_name from low; 
 
 
 
 
-- 14.funnel showing enrolled,active and completed learners--

(SELECT 'Enrolled' AS stage, COUNT(DISTINCT student_id) AS learners FROM enrollments)
UNION ALL
(SELECT 'Active', COUNT(DISTINCT e.student_id) FROM enrollments e
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
WHERE cp.completed_percent > 0)
UNION ALL
(SELECT 'Completed', COUNT(DISTINCT e.student_id) FROM enrollments e
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
WHERE cp.completed_percent = 100);



-- 15.students enrolled in more than one course

select  distinct s.student_id,s.full_name,count(e.enrollment_id) as enrolls from students s join enrollments e
on s.student_id=e.student_id
group by s.student_id,s.full_name
having count(e.enrollment_id) >1;



-- 16.students contributing to top 80% revenue
with A as
(select s.student_id,s.full_name ,
sum(c.price)  as revenue
from students s join enrollments e on s.student_id=e.student_id join courses c on
e.course_id=c.course_id group by s.student_id,s.full_name),
B as
(select *,sum(revenue) over() as total_revenue,
sum(revenue) over (order by revenue desc) as running_revenue
from A)
select student_id,full_name,revenue from B
where running_revenue<=0.8*total_revenue
order by revenue desc;


-- 17.identify months with highest enrollment activity

select monthname(enroll_date) as month,count(enrollment_id) as enrolls
from enrollments
group by month having count(enrollment_id)=(select max(cmt) from
(select count(*) as cmt from enrollments group by monthname(enroll_date))t);



-- 18.students whose course engagement is declining over time--


SELECT DISTINCT student_id,full_name
FROM (SELECT
e.student_id,s.full_name,e.enroll_date,cp.completed_percent,
LAG(cp.completed_percent) OVER (PARTITION BY e.student_id 
ORDER BY e.enroll_date) AS prev_completion
FROM students s join enrollments e on s.student_id=e.student_id
JOIN course_progress cp 
ON e.enrollment_id = cp.enrollment_id
) t
WHERE prev_completion IS NOT NULL AND completed_percent < prev_completion;
  
  
  
  
  -- 19.courses that bring most new students on signup day

SELECT c.course_id,c.course_name,COUNT(*) AS new_students
FROM students s JOIN enrollments e ON s.student_id = e.student_id
JOIN courses c ON e.course_id = c.course_id
WHERE s.signup_date = e.enroll_date
GROUP BY c.course_id, c.course_name ORDER BY new_students DESC;



-- 20. a platform level summary showing student count,activity and learning health

SELECT
COUNT(DISTINCT s.student_id) AS total_students,
COUNT(DISTINCT e.student_id) AS active_students,
COUNT(e.enrollment_id) AS total_enrollments,
ROUND(AVG(cp.completed_percent), 2) AS avg_completion_percent,
ROUND(100 * SUM(CASE WHEN cp.completed_percent = 100 THEN 1 ELSE 0 END) / COUNT(cp.enrollment_id),2)
AS completion_rate_percent FROM students s
LEFT JOIN enrollments e ON s.student_id = e.student_id
LEFT JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id;
